server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/hla
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true