server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hla
    username: cohort2e
    password: cohort2e
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true