server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/hla
    username: hlauser
    password: hlapassword
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true