DROP TYPE IF EXISTS status CASCADE;
CREATE TYPE status AS ENUM ('REVIEW','REVIEWED','APPROVED_AND_EMAIL_SENT');
CREATE CAST (VARCHAR AS status) WITH INOUT AS IMPLICIT;
ALTER TABLE schedule_entity add status status not null default 'REVIEW';