DROP TYPE IF EXISTS status CASCADE;
CREATE TYPE status AS ENUM ('DONE','REVIEW');
CREATE CAST (VARCHAR AS status) WITH INOUT AS IMPLICIT;

DROP TYPE IF EXISTS state CASCADE;
CREATE TYPE state AS ENUM ('DONE','REVIEW');
CREATE CAST (VARCHAR AS state) WITH INOUT AS IMPLICIT;