### login admin
POST http://localhost:8085/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "john@gmail.com",
  "password": "password"
}

> {%
    client.global.set("auth_token", "Bearer " + response.body.token);
%}

### login user
POST http://localhost:8085/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "mary@gmail.com",
  "password": "password"
}

> {%
    client.global.set("auth_token", "Bearer " + response.body.token);
%}

### get email by id
GET http://localhost:8085/api/v1/emails/1
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}


### create email
POST http://localhost:8085/api/v1/emails
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

{
  "providerId": 1,
  "content": "Email content 6.",
  "userId": 1
}

### get all emails
GET http://localhost:8085/api/v1/emails
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}