name: CI - Build Backend

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - hla-product-ordering/backend/**

  jobs:
    build:
      runs-on: ubuntu-latest
      services:
        postgres:
          image: postgres
          env:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: hla
          ports:
            - 5332:5432
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

      defaults:
        run:
        working-directory: ./hla-product-ordering/backend
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v3
          with:
            distribution: 'temurin'
            java-version: '17'
            cache: 'maven'
        - name: Build and run Unit/Integration Tests with Maven
          run: mvn -ntp -B verify